spring:
  # 数据源
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: bsxc!@#123
    url: jdbc:mysql://bigdata-mysql:3306/bigdata_zipkin?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
management:
  metrics:
    web:
      server:
        auto-time-requests: false
zipkin:
  storage:
    type: mysql
sleuth:
  enabled: true