## spring security 配置
security:
  oauth2:
    client:
      client-id: ENC(KTyGa9PVSqq7WnIsfYgp0g==)      # gen
      client-secret: ENC(KTyGa9PVSqq7WnIsfYgp0g==)  # gen
      scope: server
# 数据源配置
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: bsxc!@#123
    url: jdbc:mysql://bigdata-mysql:3306/bigdata?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true
  resources:
    static-locations: classpath:/static/,classpath:/views/
