## spring security 配置
security:
  oauth2:
    client:
      client-id: ENC(K+RvUHjIeAexfsFI1QWnyA==)      #daemon
      client-secret: ENC(K+RvUHjIeAexfsFI1QWnyA==)  #daemon
      scope: server
## 定时任务
spring:
  # 保存定时任务的数据源
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: bsxc!@#123
    url: jdbc:mysql://bigdata-mysql:3306/bigdata_daemon?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
  elasticjob:
    # 分布式任务协调依赖zookeeper
    zookeeper:
      server-lists: bigdata-zookeeper:2181
      namespace: bigdata-daemon
    # 普通任务
    simples:
      spring-simple-job:
        job-class: com.bosssoft.bigdata.daemon.job.BosxSimpleJob
        cron: 0 0 0/1 * * ?
        sharding-total-count: 3
        sharding-item-parameters: 0=service1,1=service2,2=service3
        eventTraceRdbDataSource: 'dataSource'
        listener:
          listener-class: com.bosssoft.bigdata.daemon.listener.BosxElasticJobListener
      spring-simple-job2:
        job-class: com.bosssoft.bigdata.daemon.job.BosxSimpleJob2
        cron: 0 0 0/1 * * ?
        sharding-total-count: 3
        sharding-item-parameters: 0=service1,1=service2,2=service3
        eventTraceRdbDataSource: 'dataSource'
        listener:
          listener-class: com.bosssoft.bigdata.daemon.listener.BosxElasticJobListener
    # 简单任务
    dataflows:
      spring-dataflow-job:
        job-class: com.bosssoft.bigdata.daemon.job.BosxDataflowJob
        cron: 0 0 0/1 * * ?
        sharding-total-count: 3
        sharding-item-parameters: 0=service1,1=service2,2=service3
        streaming-process: true
        eventTraceRdbDataSource: 'dataSource'
        listener:
          distributed-listener-class: com.bosssoft.bigdata.daemon.listener.BosxDistributeElasticJobListener
          started-timeout-milliseconds: 5000
          completed-timeout-milliseconds: 10000
