## spring security 配置
security:
  oauth2:
    client:
      client-id: ENC(3ZLPfPwewUvP2/zuTY411A==)      # bos
      client-secret: ENC(3ZLPfPwewUvP2/zuTY411A==)  # bos
      scope: server
      # 默认放行url,子模块重写时application-dev.yml中的公共配置会被覆盖,所以要把公共配置中的放行url再写一次
      ignore-urls:
        - /actuator/**
        - /v2/api-docs
        - /mobile/**  #暂时放行

# 数据源
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    # 数据库后期改成微服务库： bigdata_aggregation
    url: jdbc:mysql://192.168.1.170:3306/bigdata_aggregation?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true


