## spring security 配置
security:
  oauth2:
    client:
      ##默认放行url,子模块重写时application-dev.yml中的公共配置会被覆盖，所以要把公共配罡中的放行urZ再写一次
      ignore-urls:
        - /actuator/**
        - /v2/api-docs
        - /test/**  #添加我们模块忽略security的路径 test就是我们controller开始的

server:
  servlet:
    session:
      timeout: 30
    context-path: /info
  port: 9527
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: information
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  messages:
    encoding: UTF-8
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.18.167.15:3306/hfmp_information?characterEncoding=utf8&useSSL=false
    username: root
    password: root_123
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
swagger:
  enabled: true
# 注册中心配置
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://bos:bos@bigdata-eureka:8761/eureka/